# Generated by Django 6.0.2 on 2026-03-01 01:01

from django.db import migrations


def assign_owner_to_existing(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    Product = apps.get_model('inventory', 'Product')
    Category = apps.get_model('inventory', 'Category')
    first_superuser = User.objects.filter(is_superuser=True).order_by('id').first()
    if first_superuser:
        Product.objects.filter(owner__isnull=True).update(owner=first_superuser)
        Category.objects.filter(owner__isnull=True).update(owner=first_superuser)


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_category_owner_product_owner'),
    ]

    operations = [
        migrations.RunPython(assign_owner_to_existing, migrations.RunPython.noop),
    ]
