# Generated by Django 6.0.2 on 2026-02-25 17:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CompanyProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(help_text='Полное название вашей компании', max_length=255, verbose_name='Название компании')),
                ('short_name', models.CharField(blank=True, help_text='Для использования в документах', max_length=100, verbose_name='Короткое название')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('website', models.URLField(blank=True, verbose_name='Веб-сайт')),
                ('address', models.TextField(blank=True, verbose_name='Адрес')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Город')),
                ('inn', models.CharField(blank=True, max_length=50, verbose_name='ИНН')),
                ('bank_account', models.CharField(blank=True, max_length=100, verbose_name='Расчётный счёт')),
                ('bank_name', models.CharField(blank=True, max_length=255, verbose_name='Название банка')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='company_logos/', verbose_name='Логотип')),
                ('currency', models.CharField(default='сом', help_text='Название валюты для документов', max_length=10, verbose_name='Валюта')),
                ('footer_text', models.TextField(blank=True, help_text='Будет отображаться внизу договоров и чеков', verbose_name='Текст в подвале документов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_company', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Профиль компании',
                'verbose_name_plural': 'Профили компании',
            },
        ),
    ]
