# Generated by Django 6.0.2 on 2026-02-07 14:56

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0001_initial'),
        ('inventory', '0001_initial'),
        ('rental', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderitem',
            options={'verbose_name': 'Товар в заказе', 'verbose_name_plural': 'Товары в заказе'},
        ),
        migrations.AlterModelOptions(
            name='payment',
            options={'ordering': ['-payment_date'], 'verbose_name': 'Оплата', 'verbose_name_plural': 'Оплаты'},
        ),
        migrations.AlterModelOptions(
            name='rentalorder',
            options={'ordering': ['-created_at'], 'verbose_name': 'Заказ аренды', 'verbose_name_plural': 'Заказы аренды'},
        ),
        migrations.AlterModelOptions(
            name='returndocument',
            options={'ordering': ['-return_date'], 'verbose_name': 'Возврат', 'verbose_name_plural': 'Возвраты'},
        ),
        migrations.AlterModelOptions(
            name='returnitem',
            options={'verbose_name': 'Товар в возврате', 'verbose_name_plural': 'Товары в возврате'},
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='current_total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Текущая стоимость'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='issued_date',
            field=models.DateTimeField(verbose_name='Дата выдачи'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rental.rentalorder', verbose_name='Заказ'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='original_total_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Изначальная стоимость'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='planned_return_date',
            field=models.DateTimeField(verbose_name='Планируемая дата возврата'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_per_day',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена/день'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='price_per_hour',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена/час'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='inventory.product', verbose_name='Товар'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_remaining',
            field=models.PositiveIntegerField(verbose_name='Осталось штук'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_returned',
            field=models.PositiveIntegerField(default=0, verbose_name='Возвращено штук'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='quantity_taken',
            field=models.PositiveIntegerField(verbose_name='Взято штук'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='rental_days',
            field=models.PositiveIntegerField(default=1, verbose_name='Дней аренды'),
        ),
        migrations.AlterField(
            model_name='orderitem',
            name='rental_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Часов аренды'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создано'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата оплаты'),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rental_orders', to='clients.client', verbose_name='Клиент'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Дата создания'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='rentalorder',
            name='status',
            field=models.CharField(choices=[('open', 'Открыт'), ('closed', 'Закрыт')], default='open', max_length=20, verbose_name='Статус'),
        ),
        migrations.AlterField(
            model_name='returndocument',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='Создан'),
        ),
        migrations.AlterField(
            model_name='returndocument',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='returndocument',
            name='return_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата возврата'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='actual_days',
            field=models.PositiveIntegerField(verbose_name='Фактически дней'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='actual_hours',
            field=models.PositiveIntegerField(default=0, verbose_name='Фактически часов'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='calculated_cost',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Стоимость по факту'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='notes',
            field=models.TextField(blank=True, verbose_name='Примечания'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='order_item',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='returns', to='rental.orderitem', verbose_name='Товар из заказа'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='quantity',
            field=models.PositiveIntegerField(verbose_name='Возвращено штук'),
        ),
        migrations.AlterField(
            model_name='returnitem',
            name='return_document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='rental.returndocument', verbose_name='Документ возврата'),
        ),
    ]
