# Generated by Django 6.0.2 on 2026-02-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0002_alter_orderitem_options_alter_payment_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод'), ('credit', 'Зачёт аванса')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
