# Generated by Django 6.0.2 on 2026-02-20 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0003_alter_payment_payment_method'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='actual_cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Фактическая стоимость'),
        ),
    ]
