# Generated by Django 6.0.2 on 2026-02-24 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0004_orderitem_actual_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='order_code',
            field=models.CharField(blank=True, db_index=True, help_text='Уникальный код заказа (ФИО-1, ФИО-2...)', max_length=50, verbose_name='Код заказа'),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='order_number',
            field=models.PositiveIntegerField(blank=True, help_text='Порядковый номер заказа для этого клиента (#1, #2, #3...)', null=True, verbose_name='Номер заказа клиента'),
        ),
    ]
