# Generated by Django 6.0.2 on 2026-02-28 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0005_rentalorder_order_code_rentalorder_order_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='orders/proofs/', verbose_name='Доказательство (фото/аудио)'),
        ),
    ]
