# Generated by Django 6.0.1 on 2026-03-02 16:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0006_add_proof_file_to_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderExcludedDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='Дата')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлено')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='excluded_days', to='rental.rentalorder', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Исключённый день',
                'verbose_name_plural': 'Исключённые дни (дождь)',
                'ordering': ['date'],
                'unique_together': {('order', 'date')},
            },
        ),
    ]
