# Generated by Django 6.0.1 on 2026-03-06 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0009_returnitem_repair_fee'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='delivery_address',
            field=models.CharField(blank=True, max_length=500, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='delivery_plate',
            field=models.CharField(blank=True, max_length=50, verbose_name='Номер авто'),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='delivery_vehicle',
            field=models.CharField(blank=True, max_length=200, verbose_name='Автомобиль'),
        ),
        migrations.AddField(
            model_name='rentalorder',
            name='has_delivery',
            field=models.BooleanField(default=False, verbose_name='Доставка'),
        ),
    ]
