# Generated by Django 6.0.1 on 2026-03-06 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0010_delivery_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='rentalorder',
            name='delivery_cost',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Стоимость доставки'),
        ),
    ]
