# Generated by Django 6.0.1 on 2026-03-17 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rental', '0013_orderitem_rain_applicable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Наличные'), ('card', 'Карта'), ('transfer', 'Перевод'), ('credit', 'Зачёт аванса'), ('writeoff', 'Списание долга')], default='cash', max_length=20, verbose_name='Способ оплаты'),
        ),
    ]
