# Generated by Django 6.0.2 on 2026-02-28 01:08

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0002_client_telegram_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientphone',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message='Введите номер в формате +996XXXXXXXXX или +7XXXXXXXXXX', regex='^\\+(996\\d{9}|7\\d{10})$')], verbose_name='Номер'),
        ),
    ]
