# Generated by Django 6.0.2 on 2026-02-28 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0003_alter_clientphone_phone_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='proof_file',
            field=models.FileField(blank=True, null=True, upload_to='passports/proof/', verbose_name='Доказательство (фото/аудио)'),
        ),
    ]
