# Generated by Django 6.0.2 on 2026-02-28 01:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0004_client_proof_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='proof_file',
        ),
    ]
