# Generated by Django 6.0.2 on 2026-03-01 01:00

from django.db import migrations


def assign_owner_to_existing(apps, schema_editor):
    """Назначить владельца существующим клиентам — первый суперпользователь."""
    User = apps.get_model('auth', 'User')
    Client = apps.get_model('clients', 'Client')
    first_superuser = User.objects.filter(is_superuser=True).order_by('id').first()
    if first_superuser:
        Client.objects.filter(owner__isnull=True).update(owner=first_superuser)


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0006_client_owner'),
    ]

    operations = [
        migrations.RunPython(assign_owner_to_existing, migrations.RunPython.noop),
    ]
