# Generated by Django 6.0.1 on 2026-03-14 16:21

import apps.clients.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clients', '0008_client_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client',
            name='passport_back',
            field=models.ImageField(blank=True, null=True, upload_to=apps.clients.models.passport_back_path, verbose_name='Паспорт (обратная)'),
        ),
        migrations.AlterField(
            model_name='client',
            name='passport_front',
            field=models.ImageField(blank=True, null=True, upload_to=apps.clients.models.passport_front_path, verbose_name='Паспорт (лицевая)'),
        ),
    ]
