# Generated by Django 6.0.2 on 2026-03-01 01:01

from django.db import migrations


def create_profiles(apps, schema_editor):
    """Создать UserProfile для существующих пользователей."""
    User = apps.get_model('auth', 'User')
    UserProfile = apps.get_model('main', 'UserProfile')
    for user in User.objects.all():
        UserProfile.objects.get_or_create(user=user, defaults={'owner': None})


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_profiles, migrations.RunPython.noop),
    ]
