# Generated by Django 6.0.2 on 2026-03-01 16:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_create_profiles_for_existing_users'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='max_warehouses',
            field=models.PositiveIntegerField(default=1, help_text='Устанавливается создателем системы', verbose_name='Макс. складов'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('director', 'Директор'), ('employee', 'Сотрудник')], default='director', max_length=20, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='team_members', to=settings.AUTH_USER_MODEL, verbose_name='Директор компании'),
        ),
        migrations.CreateModel(
            name='DirectorMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Отправлено')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('sender', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL, verbose_name='Отправитель')),
            ],
            options={
                'verbose_name': 'Сообщение директора',
                'verbose_name_plural': 'Сообщения директоров',
                'ordering': ['-created_at'],
            },
        ),
    ]
