# Generated by Django 6.0.2 on 2026-03-01 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_data_set_director_roles'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(choices=[('create_order', 'Создал заказ'), ('close_order', 'Закрыл заказ'), ('edit_order', 'Изменил заказ'), ('accept_payment', 'Принял оплату'), ('create_client', 'Создал клиента'), ('edit_client', 'Изменил клиента'), ('create_product', 'Создал товар'), ('edit_product', 'Изменил товар'), ('return_items', 'Оформил возврат'), ('other', 'Другое')], default='other', max_length=50, verbose_name='Действие')),
                ('description', models.TextField(verbose_name='Описание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Время')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Лог активности',
                'verbose_name_plural': 'Лог активности',
                'ordering': ['-created_at'],
            },
        ),
    ]
