# Generated by Django 6.0.2 on 2026-03-01 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_activitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='needs_company_setup',
            field=models.BooleanField(default=False, verbose_name='Требует настройки компании'),
        ),
    ]
