# Generated by Django 6.0.1 on 2026-03-14 16:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0013_notification'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=150, verbose_name='Логин')),
                ('ip', models.GenericIPAddressField(blank=True, null=True, verbose_name='IP-адрес')),
                ('method', models.CharField(max_length=10, verbose_name='Метод')),
                ('path', models.CharField(max_length=500, verbose_name='URL')),
                ('query', models.CharField(blank=True, max_length=500, verbose_name='Параметры')),
                ('status_code', models.PositiveSmallIntegerField(verbose_name='Статус')),
                ('response_ms', models.PositiveIntegerField(default=0, verbose_name='Время ответа (мс)')),
                ('user_agent', models.CharField(blank=True, max_length=500, verbose_name='User-Agent')),
                ('referer', models.CharField(blank=True, max_length=500, verbose_name='Referer')),
                ('event', models.CharField(blank=True, max_length=50, verbose_name='Событие')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Время')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Запрос',
                'verbose_name_plural': 'Лог запросов',
                'ordering': ['-created_at'],
            },
        ),
    ]
