# Generated by Django 6.0.1 on 2026-03-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_request_log'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Номер телефона для связи', max_length=30, verbose_name='Телефон'),
        ),
    ]
